<?php

namespace app\models;
use app\core\UserModel;

class User extends UserModel
{
    const STATUS_INACTIVE=0;
    const STATUS_ACTIVE=1;
    const STATUS_DELETE=2;

    public string $firstname="";
    public string $lastname="";
    public string $email="";
    public int $status=self::STATUS_INACTIVE;
    public string $password="";
    public string $confirmPassword="";

    public function register(){
        return $this->save();
    }

    public function save()
    {
        $this->status=self::STATUS_INACTIVE;
        $this->password=password_hash($this->password,PASSWORD_DEFAULT);
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
       return [
           'firstname'=>[self::RULE_REQUIRED],
           'lastname'=>[self::RULE_REQUIRED],
           'email'=>[self::RULE_REQUIRED,self::RULE_EMAIL,[self::RULE_UNIQUE,'class'=>self::class]],
           'password'=>[self::RULE_REQUIRED,[self::RULE_MIN,'min'=>8],[self::RULE_MAX,'max'=>24]],
           'confirmPassword'=>[self::RULE_REQUIRED,[self::RULE_MATCH,'match'=>'password']],
       ];

    }

    public function tableName(): string
    {
        // TODO: Implement tableName() method.
        return 'users';
    }

    public function attributes(): array
    {
        // TODO: Implement attributes() method.
        return ['firstname','lastname','email','password','status'];
    }

    public function labels(): array
    {
        return [
            'firstname'=>'First name',
            'lastname'=>'Last name',
            'email'=>'Email',
            'password'=>'Password',
            'confirmPassword'=>'Confirm Password'
        ];
    }

    public function primaryKey(): string
    {
        return 'id';
        // TODO: Implement primaryKey() method.
    }

    public function getDisplayName(): string
    {
        // TODO: Implement getDisplayName() method.
        return 'Welcome '.$this->firstname.' '.$this->lastname;
    }
}